export const INSTANCES = {
  ADD_NEW_INSTANCE_STARTS: "ADD_NEW_INSTANCE_STARTS",
  ACCEPT_INSTANCE_STARTS: "ACCEPT_INSTANCE_STARTS",
  CANCEL_INSTANCE_STARTS: "CANCEL_INSTANCE_STARTS",
  UPLOAD_PROOF_STARTS: "UPLOAD_PROOF_STARTS",
  TOGGLE_PROOF_PUBLIC_PRIVATE_STARTS: "TOGGLE_PROOF_PUBLIC_PRIVATE_STARTS",
  VALIDATE_PROOF_STARTS: "VALIDATE_PROOF_STARTS",
  INVALIDATE_PROOF_STARTS: "INVALIDATE_PROOF_STARTS",
  ADD_LIKE_TO_PROOF_STARTS: "ADD_LIKE_TO_PROOF_STARTS",
  ADD_DISLIKE_TO_PROOF_STARTS: "ADD_DISLIKE_TO_PROOF_STARTS",
  ADD_COMMENT_TO_PROOF_STARTS: "ADD_COMMENT_TO_PROOF_STARTS",
  EDIT_COMMENT_AT_PROOF_STARTS: "EDIT_COMMENT_AT_PROOF_STARTS",
  DELETE_COMMENT_FROM_PROOF_STARTS: "DELETE_COMMENT_FROM_PROOF_STARTS",
  REPORT_COMMENT_ABUSE_AT_PROOF_STARTS: "REPORT_COMMENT_ABUSE_AT_PROOF_STARTS",
  REPORT_GLOBAL_VALIDATOR_STARTS: "REPORT_GLOBAL_VALIDATOR_STARTS"
};
