export const INSTANCES = {
  ADD_NEW_INSTANCE_STARTS: "ADD_NEW_INSTANCE_STARTS",
  ACCEPT_INSTANCE_STARTS: "ACCEPT_INSTANCE_STARTS",
  CANCEL_INSTANCE_STARTS: "CANCEL_INSTANCE_STARTS",
  UPLOAD_PROOF_STARTS: "UPLOAD_PROOF_STARTS",
  TOGGLE_PROOF_PUBLIC_PRIVATE_STARTS: "TOGGLE_PROOF_PUBLIC_PRIVATE_STARTS",
  VALIDATE_PROOF_STARTS: "VALIDATE_PROOF_STARTS",
  INVALIDATE_PROOF_STARTS: "INVALIDATE_PROOF_STARTS"
};
