export const USER = {
  GOOGLE_SIGN_IN_STARTS: "GOOGLE_SIGN_IN_STARTS",
  EMAIL_PASSWORD_SIGN_IN_STARTS: "EMAIL_PASSWORD_SIGN_IN_STARTS",
  // SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  // SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_STARTS: "SIGN_OUT_STARTS",
  // SIGN_OUT_SUCCESS: "SIGN_OUT_SUCESS",
  // SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  // CHECK_USER_SESSION_STARTS: "CHECK_USER_SESSION_STARTS",
  // CHECK_USER_SESSION_END: "CHECK_USER_SESSION_END",
  SIGN_UP_STARTS: "SIGN_UP_STARTS",
  // SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  // SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  UPDATE_AVATAR_STARTS: "UPDATE_AVATAR_STARTS"
  // UPDATE_AVATAR_SUCCESS: "UPDATE_AVATAR_SUCCESS",
  // UPDATE_AVATAR_FAILURE: "UPDATE_AVATAR_FAILURE"
};
