export const USER = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  EMAIL_PASSWORD_SIGN_IN_START: "EMAIL_PASSWORD_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_END: "CHECK_USER_SESSION_END",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  UPDATE_AVATAR_START: "UPDATE_AVATAR_START",
  UPDATE_AVATAR_SUCCESS: "UPDATE_AVATAR_SUCCESS",
  UPDATE_AVATAR_FAILURE: "UPDATE_AVATAR_FAILURE"
};
